## Basic NumPy Arrays

Vectors 

1. Create a nparray from a list, a dict and a tuple.

2. Index elements using slice notation and element by element notation. Try to get an array output and a non-array output.


In [15]:
import numpy as np
import sys

In [3]:
from_list = np.array([1, 2, 3, 4])
from_list

array([1, 2, 3, 4])

In [4]:
from_tuple = np.array((1, 2, 3, 4))
from_tuple

array([1, 2, 3, 4])

In [6]:
from_dict = np.array({1, 2, 3, 4})
from_dict

array({1, 2, 3, 4}, dtype=object)

From a dict is diferent than expected

In [8]:
fl = from_tuple
ft = from_list

In [10]:
fl[0], fl[3]

(1, 4)

In [11]:
fl[[0, 3]]

array([1, 4])

In [12]:
fl[0:2]

array([1, 2])

## Data Type

1. Display the dtype of one or more arrays.

2. Create an array and make explicit the dtype.


In [13]:
fl.dtype

dtype('int64')

In [16]:
np.array([[1,2], sys]).dtype

<ipython-input-16-c60b087236f5>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2], sys]).dtype


dtype('O')

In [17]:
a = np.array([1, 2, 3, 4], dtype = np.int8)

In [18]:
a

array([1, 2, 3, 4], dtype=int8)

In [19]:
b = np.array((1, 2, 3, 4), dtype=np.float)

<ipython-input-19-ceca0504a9f1>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.array((1, 2, 3, 4), dtype=np.float)


In [20]:
b.dtype

dtype('float64')

## Matrix, dimensions and shapes

1. Use shape, ndim and size over a nparray.

2. Create a non-consistent array an display its type. 

In [21]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [22]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matrix.shape

(3, 3)

In [24]:
matrix.ndim

2

In [25]:
matrix.size

9

In [26]:
m2 = np.array([[[1, 2, 3], [4, 5, 6], [7,8,9]], 
               [[10,11,12], [13,14,15], [16,17,18]],
               [[19,20,21], [22,23,24], [25,26,27]]])
m2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [28]:
m2.shape

(3, 3, 3)

In [29]:
m2.ndim

3

In [30]:
m2.size

27

In [34]:
m2[2][2][2]

27

# Index and slicing of matrices

1. Index columns and rows with slices. 
2. replace rows or columns in a matrix with a vector.

In [35]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [38]:
matrix[1,1]

5

In [40]:
matrix[1,1] = 1000000
matrix

array([[      1,       2,       3],
       [      4, 1000000,       6],
       [      7,       8,       9]])

In [43]:
matrix[1]=0
matrix

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [44]:
matrix[:,1]=0
matrix

array([[1, 0, 3],
       [0, 0, 0],
       [7, 0, 9]])

## Summary Statistics

1. Create a vector and a matrix. Aply over them sum, mean, std, var, cumsum, prod, cumprod.

2. Aply the same operations over axis in the matrix only. 

In [47]:
vec = np.array([7, 6, 5, 4, 3, 2, 1])
mat = np.array([[1, 1, 1],
               [2, 2, 2],
               [3, 3, 3]])

In [49]:
vec.cumprod()

array([   7,   42,  210,  840, 2520, 5040, 5040])

In [51]:
mat.cumsum()

array([ 1,  2,  3,  5,  7,  9, 12, 15, 18])

In [53]:
mat.mean()

2.0

In [55]:
mat.std()

0.816496580927726

In [56]:
mat.var()

0.6666666666666666

In [57]:
mat.sum(axis = 0)

array([6, 6, 6])

In [58]:
mat.sum(axis = 1)

array([3, 6, 9])

## Broadcasting and vectorized operations

1. create vectors and operate them with basic math operators (+, -, *, etc)

2. operate vectors and matrices

In [67]:
v1 = np.arange(11)
v2 = np.array([10,9,8,7,6,5,4,3,2,1,0])

In [68]:
v1+v2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [69]:
v1*v2

array([ 0,  9, 16, 21, 24, 25, 24, 21, 16,  9,  0])

In [74]:
np.array(v1[1:]/v2[:-1]).round(2)

array([ 0.1 ,  0.22,  0.38,  0.57,  0.83,  1.2 ,  1.75,  2.67,  4.5 ,
       10.  ])

In [75]:
(v1+v2)*4

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [79]:
(1/v1[1:]).round(2)

array([1.  , 0.5 , 0.33, 0.25, 0.2 , 0.17, 0.14, 0.12, 0.11, 0.1 ])

In [81]:
((1/v1[1:])*100).round(2)

array([100.  ,  50.  ,  33.33,  25.  ,  20.  ,  16.67,  14.29,  12.5 ,
        11.11,  10.  ])

## Boolean Arrays

1. Index over a vector manually using booleans. 
2. make a query over a non boolean type vector which returns a boolean.
3. use the last query (or another) for make a real query over the vector.
4. use a math operator as .mean() for to do a query.
5. do the same with a matrix
6. Use |, &, ==, ^ operators in your querys

In [85]:
v3 = np.arange(4)
v3[[True, False, False, False]]

array([0])

In [86]:
v3 == 1

array([False,  True, False, False])

In [87]:
v3[v3 == 1]

array([1])

In [88]:
v4 = np.arange(11)
v4 > v4.mean() 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [89]:
(v4>v4.mean()) | (v4>v4.std())

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [90]:
(v4>v4.mean()) & (v4>v4.std()) 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [91]:
v4 == 1

array([False,  True, False, False, False, False, False, False, False,
       False, False])

In [92]:
v4 ^ 1

array([ 1,  0,  3,  2,  5,  4,  7,  6,  9,  8, 11])